# Generated by Django 2.2.5 on 2020-02-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='yqdx_hwz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=11, null='空', verbose_name='手机号')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('sfzh', models.CharField(max_length=18, null=True, verbose_name='身份证号')),
                ('hjdz', models.CharField(max_length=500, null=True, verbose_name='户籍地址')),
                ('xzdz', models.CharField(max_length=500, null=True, verbose_name='现住地址')),
                ('ssjd', models.CharField(default='空', max_length=20, verbose_name='所属街道')),
                ('is_wuhan', models.CharField(max_length=1, null=True, verbose_name='是否武汉')),
                ('is_hubei', models.CharField(max_length=1, null=True, verbose_name='是否湖北')),
                ('is_not_zhenhai', models.CharField(max_length=1, null=True, verbose_name='市内非镇海')),
                ('is_not_ningbo', models.CharField(max_length=1, null=True, verbose_name='省内非宁波')),
                ('is_not_zhejiang', models.CharField(max_length=1, null=True, verbose_name='是否省外')),
                ('back_provinces', models.CharField(max_length=20, null=True, verbose_name='返回省')),
                ('back_city', models.CharField(max_length=20, null=True, verbose_name='返回市')),
                ('back_year', models.CharField(default='2020', max_length=4, verbose_name='返回年')),
                ('back_month', models.CharField(max_length=2, null=True, verbose_name='返回月')),
                ('back_day', models.CharField(max_length=2, null=True, verbose_name='返回日')),
                ('status', models.CharField(default='空', max_length=10, verbose_name='当前状态')),
                ('status_remarks', models.CharField(max_length=500, null=True, verbose_name='当前状态备注')),
                ('call_detail', models.CharField(default='空', max_length=100, verbose_name='拨打情况')),
                ('self_tell', models.CharField(max_length=100, null=True, verbose_name='自述情况')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('from_source', models.CharField(default='市局下发', max_length=50, verbose_name='数据来源')),
                ('gkr', models.CharField(max_length=20, null=True, verbose_name='管控人')),
                ('gkr_phone', models.CharField(max_length=11, null=True, verbose_name='管控人电话')),
                ('other1', models.CharField(max_length=500, null=True, verbose_name='备用3')),
                ('other2', models.CharField(max_length=500, null=True, verbose_name='备用4')),
                ('other3', models.CharField(max_length=500, null=True, verbose_name='备用5')),
                ('white_list_flag', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.list_type', to_field='type_value')),
            ],
            options={
                'verbose_name': '疫情对象话务组',
                'verbose_name_plural': '疫情对象话务组',
                'db_table': 'yqdx_hwz',
            },
        ),
    ]
